//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Malaffi.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabTechnician
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LabTechnician()
        {
            this.Tests = new HashSet<Test>();
        }
    
        public int Id { get; set; }
        public string UserId { get; set; }
        public int CommercialRegistrationNo { get; set; }
        public string FullName { get; set; }
        public int MedicaSpecializationId { get; set; }
        public string Address { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual MedicaSpecializationType MedicaSpecializationType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Test> Tests { get; set; }
    }
}
