//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Malaffi.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicineRequest
    {
        public int Id { get; set; }
        public int PatientId { get; set; }
        public int DoctorId { get; set; }
        public string TotalQuantity { get; set; }
        public string PerDayQuantity { get; set; }
        public Nullable<int> PharmacistId { get; set; }
        public int MedicineId { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual Medicine Medicine { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual Pharmacist Pharmacist { get; set; }
    }
}
